/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFRAZ;

/**
 *
 * @author YOSHUA
 */

import PER_de_cada_clase.VisitanteDAO;
import proyectoprogra3.*;
import javax.swing.table.DefaultTableModel;//
import java.util.*;//
import javax.swing.*;//

import javax.swing.JOptionPane;
import java.awt.event.*;//
public class Registo_Visitantes extends javax.swing.JFrame {
    private DefaultTableModel modeloTabla;
    //visitante
    private List<Visitante> listaVisitantes=new ArrayList<>();
    private VisitanteDAO dao=new VisitanteDAO();
    private CSimpleV CSVis=new CSimpleV();
    /**
     * Creates new form Registo_Visitantes
     */
    public Registo_Visitantes() {
        initComponents();
        modeloTabla =(DefaultTableModel)TABLA_VISITANTES.getModel();
        cargarVisitantes();
        
        TABLA_VISITANTES.getSelectionModel().addListSelectionListener(e -> {
            int fila = TABLA_VISITANTES.getSelectedRow();
            if(fila !=-1){
                Visitante v=listaVisitantes.get(fila);
                TFci_visitante.setText(String.valueOf(v.getCi()));
                TFnombre_visitante.setText(v.getNombre());
                TFpaterno_visitante.setText(v.getPaterno());
                TFmaterno_visitante.setText(v.getMaterno());
                TFedad_visitante.setText(String.valueOf(v.getEdad()));
                TFsexo_visitante.setText(v.getSexo());
                TFcontacto_visitante.setText(String.valueOf(v.getContacto()));
                TF_id_visitante.setText(String.valueOf(v.getId_Visitante()));
                TF_id_fecha_medica_vis.setText(String.valueOf(v.getId_FichasMedicas()));
                TF_id_informaciones_vis.setText(String.valueOf(v.getId_Informaciones()));
               
            }
        });
    }
    
    public void cargarVisitantes(){
        listaVisitantes=dao.cargaVisitantes();
        modeloTabla.setRowCount(0);
        for(Visitante v: listaVisitantes){
            if(v.getCi()>0)
            {
                modeloTabla.addRow(new Object[]{v.getCi(), v.getNombre(),v.getPaterno(),v.getMaterno(),v.getEdad(),v.getSexo(),v.getContacto(),v.getId_Visitante(),v.getId_FichasMedicas(),v.getId_Informaciones()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TFci_visitante = new javax.swing.JTextField();
        TFnombre_visitante = new javax.swing.JTextField();
        TFpaterno_visitante = new javax.swing.JTextField();
        TFmaterno_visitante = new javax.swing.JTextField();
        TFedad_visitante = new javax.swing.JTextField();
        TFsexo_visitante = new javax.swing.JTextField();
        TFcontacto_visitante = new javax.swing.JTextField();
        TF_id_visitante = new javax.swing.JTextField();
        TF_id_fecha_medica_vis = new javax.swing.JTextField();
        TF_id_informaciones_vis = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_VISITANTES = new javax.swing.JTable();
        BTNAgregar_visitante = new javax.swing.JButton();
        BTNEditar_visitante = new javax.swing.JButton();
        Eliminar_visitante = new javax.swing.JButton();
        BTNLlenar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 60)); // NOI18N
        jLabel11.setText("FERIA DE SALUD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 850, 100));
        getContentPane().add(TFci_visitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, -1));
        getContentPane().add(TFnombre_visitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 140, -1));

        TFpaterno_visitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFpaterno_visitanteActionPerformed(evt);
            }
        });
        getContentPane().add(TFpaterno_visitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 140, -1));
        getContentPane().add(TFmaterno_visitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 140, -1));
        getContentPane().add(TFedad_visitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 140, -1));
        getContentPane().add(TFsexo_visitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 140, -1));
        getContentPane().add(TFcontacto_visitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 140, -1));
        getContentPane().add(TF_id_visitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 140, -1));
        getContentPane().add(TF_id_fecha_medica_vis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 140, -1));

        TF_id_informaciones_vis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_id_informaciones_visActionPerformed(evt);
            }
        });
        getContentPane().add(TF_id_informaciones_vis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 140, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PATERNO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MATERNO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EDAD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("sexo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("contacto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("id_vistantes");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("id_fechaMedica");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 90, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("id_informaciones");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, 30));

        TABLA_VISITANTES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CI", "NOMBRE", "PATERNO", "MATERNO", "EDAD", "SEXO", "Title 7", "Title 8", ""
            }
        ));
        jScrollPane1.setViewportView(TABLA_VISITANTES);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 820, 130));

        BTNAgregar_visitante.setBackground(new java.awt.Color(0, 0, 255));
        BTNAgregar_visitante.setForeground(new java.awt.Color(255, 255, 255));
        BTNAgregar_visitante.setText("Agregar");
        BTNAgregar_visitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAgregar_visitanteActionPerformed(evt);
            }
        });
        getContentPane().add(BTNAgregar_visitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 130, 30));

        BTNEditar_visitante.setBackground(new java.awt.Color(255, 255, 0));
        BTNEditar_visitante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTNEditar_visitante.setText("Editar");
        BTNEditar_visitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEditar_visitanteActionPerformed(evt);
            }
        });
        getContentPane().add(BTNEditar_visitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 130, -1));

        Eliminar_visitante.setBackground(new java.awt.Color(255, 0, 0));
        Eliminar_visitante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Eliminar_visitante.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar_visitante.setText("Eliminar");
        Eliminar_visitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_visitanteActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar_visitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 130, -1));

        BTNLlenar.setBackground(new java.awt.Color(0, 204, 204));
        BTNLlenar.setText("LLENAR");
        BTNLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLlenarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNLlenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNAgregar_visitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAgregar_visitanteActionPerformed
        Visitante v=new Visitante(
            Integer.parseInt(TFci_visitante.getText()),
            TFnombre_visitante.getText(),
            TFpaterno_visitante.getText(),
            TFmaterno_visitante.getText(),
            Integer.parseInt(TFedad_visitante.getText()),
            TFsexo_visitante.getText(),
            Integer.parseInt(TFcontacto_visitante.getText()),
            Integer.parseInt(TF_id_visitante.getText()),
            Integer.parseInt(TF_id_fecha_medica_vis.getText()),
            Integer.parseInt(TF_id_informaciones_vis.getText())
        );
        listaVisitantes.add(v);
        CSVis.adicionar(v);
        modeloTabla.addRow(new Object[]{v.getCi(), v.getNombre(),v.getPaterno(),v.getMaterno(),v.getEdad(),v.getSexo(),v.getContacto(),v.getId_Visitante(),v.getId_FichasMedicas(),v.getId_Informaciones()});
        dao.guardarVisitantes(listaVisitantes);
        LimpiarCampos_Visitantes();
        JOptionPane.showMessageDialog(null, "Visitante agregado correctamente");
    }//GEN-LAST:event_BTNAgregar_visitanteActionPerformed

    private void TF_id_informaciones_visActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_id_informaciones_visActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_id_informaciones_visActionPerformed

    private void TFpaterno_visitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFpaterno_visitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFpaterno_visitanteActionPerformed

    private void BTNEditar_visitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEditar_visitanteActionPerformed
        int fila =TABLA_VISITANTES.getSelectedRow();
        if(fila!=-1){
            Visitante v=listaVisitantes.get(fila);
            v.setCi(Integer.parseInt(TFci_visitante.getText()));
            v.setNombre(TFnombre_visitante.getText());
            v.setPaterno(TFpaterno_visitante.getText());
            v.setMaterno(TFmaterno_visitante.getText());
            v.setEdad(Integer.parseInt(TFedad_visitante.getText()));
            v.setSexo(TFsexo_visitante.getText());
            v.setContacto(Integer.parseInt(TFcontacto_visitante.getText()));
            v.setId_Visitante(Integer.parseInt(TF_id_visitante.getText()));
            v.setId_FichasMedicas(Integer.parseInt(TF_id_fecha_medica_vis.getText()));
            v.setId_Informaciones(Integer.parseInt(TF_id_informaciones_vis.getText()));
        }
    }//GEN-LAST:event_BTNEditar_visitanteActionPerformed

    private void Eliminar_visitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_visitanteActionPerformed
        int fila=TABLA_VISITANTES.getSelectedRow();
        if(fila!=-1){
            
        }
    }//GEN-LAST:event_Eliminar_visitanteActionPerformed

    private void BTNLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLlenarActionPerformed
        listaVisitantes = dao.cargaVisitantes();
        modeloTabla.setRowCount(0);
        CSVis = new CSimpleV(); // ← LIMPIAR COLA

        for(Visitante v : listaVisitantes){
        if(v.getCi() > 0){

            // AGREGAR A LA TABLA
            modeloTabla.addRow(new Object[]{
                v.getCi(), v.getNombre(), v.getPaterno(),
                v.getMaterno(), v.getEdad(), v.getSexo(),
                v.getContacto(), v.getId_Visitante(),
                v.getId_FichasMedicas(), v.getId_Informaciones()
            });

            // AGREGAR A LA COLA
            CSVis.adicionar(v);
        }
        CSVis.mostrar();
    }
    }//GEN-LAST:event_BTNLlenarActionPerformed
    
    public void LimpiarCampos_Visitantes(){
        TFci_visitante.setText("");
        TFnombre_visitante.setText("");
        TFpaterno_visitante.setText("");
        TFmaterno_visitante.setText("");
        TFedad_visitante.setText("");
        TFsexo_visitante.setText("");
        TFcontacto_visitante.setText("");
        TF_id_visitante.setText("");
        TF_id_fecha_medica_vis.setText("");
        TF_id_informaciones_vis.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registo_Visitantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registo_Visitantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registo_Visitantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registo_Visitantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registo_Visitantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAgregar_visitante;
    private javax.swing.JButton BTNEditar_visitante;
    private javax.swing.JButton BTNLlenar;
    private javax.swing.JButton Eliminar_visitante;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTable TABLA_VISITANTES;
    private javax.swing.JTextField TF_id_fecha_medica_vis;
    private javax.swing.JTextField TF_id_informaciones_vis;
    private javax.swing.JTextField TF_id_visitante;
    private javax.swing.JTextField TFci_visitante;
    private javax.swing.JTextField TFcontacto_visitante;
    private javax.swing.JTextField TFedad_visitante;
    private javax.swing.JTextField TFmaterno_visitante;
    private javax.swing.JTextField TFnombre_visitante;
    private javax.swing.JTextField TFpaterno_visitante;
    private javax.swing.JTextField TFsexo_visitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
